-- ============================================================================
-- overhaul_wipe.sql
-- Full reset of customer + order + downstream operational data, in preparation
-- for `overhaul_reseed.sql`.
--
-- LEAVES UNTOUCHED (per user direction):
--   • product_variant_stock / product_variants.total_stock
--   • material_stock / raw_materials.total_stock
--   • employees / branches / vehicles (vehicle status reset only)
--   • products / product_variants / raw_materials catalogs
--   • product_variant_raw_materials (BOM)
--   • agent_targets / branch_sales_targets / agent_quotas
--
-- WIPES (in FK-safe order):
--   • Trips + trip history + delivery tracking + delay exceptions + shipments
--     + warehouse_readiness
--   • POD collections, order_fulfillment + loading_details
--   • Finance: receivables, collection_notes, collection_payment_records,
--     collection_payment_links, payment_transactions, digital_receipts,
--     payment_links, invoices (cascade with orders)
--   • Ledgers: material_consumption (regenerated by reseed)
--   • Snapshots: agent_performance_snapshots
--   • Alerts: warehouse_alerts.related_order_id linked rows, agent_alerts
--     linked to orders
--   • Order child rows (auto-cascade): order_line_items, order_logs,
--     order_proof_documents, order_customer_portals,
--     production_request_orders
--   • orders
--   • Customer child rows (auto-cascade): customer_notes, customer_tasks,
--     customer_activities, customer_buying_patterns
--   • customer_assignments.customer_id (SET NULL via FK)
--   • customers
--
-- Run in: Supabase Dashboard → SQL Editor. Single transaction.
-- ============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Trips, trip history, delivery tracking, exceptions, shipments, readiness
-- -----------------------------------------------------------------------------

DELETE FROM warehouse_readiness;
DELETE FROM delivery_tracking;
DELETE FROM delay_exceptions;
DELETE FROM shipments;
DELETE FROM trip_history;

-- Detach vehicles before we drop trips so vehicles.current_trip_id FK is satisfied.
UPDATE vehicles
SET
  current_trip_id     = NULL,
  status              = 'Available',
  trips_today         = 0,
  utilization_percent = 0,
  next_available_time = NULL;

DELETE FROM trips;

-- -----------------------------------------------------------------------------
-- 2. Warehouse / fulfillment artifacts tied to orders
-- -----------------------------------------------------------------------------

-- loading_details cascades from order_fulfillment.
DELETE FROM order_fulfillment;
DELETE FROM pod_collections;

-- -----------------------------------------------------------------------------
-- 3. Finance: receivables (+ children), payment artifacts, invoices
-- -----------------------------------------------------------------------------

-- collection_notes / collection_payment_records cascade with receivables.
DELETE FROM collection_payment_links;
DELETE FROM receivables;

-- digital_receipts cascade from payment_transactions.
DELETE FROM payment_transactions;
DELETE FROM payment_links;

-- Invoices cascade their FK from orders but we delete them explicitly so the
-- orders.invoice_id FK becomes NULL before the orders DELETE runs.
UPDATE orders SET invoice_id = NULL WHERE invoice_id IS NOT NULL;
DELETE FROM invoices;

-- -----------------------------------------------------------------------------
-- 4. Ledgers & analytics snapshots tied to orders
-- -----------------------------------------------------------------------------

-- Full table wipe — reseed will regenerate from BOM × line items.
DELETE FROM material_consumption;

-- Agent / executive snapshots are derived; we regenerate as needed.
DELETE FROM agent_performance_snapshots;

-- Agent commission ledger (per agent × month). Phase 8 of the reseed
-- rebuilds this from payment proofs.
DELETE FROM agent_commissions;

-- Order-linked alerts (warehouse_alerts.related_order_id is SET NULL on order
-- delete; we want them gone instead of stale).
DELETE FROM warehouse_alerts WHERE related_order_id IS NOT NULL;
DELETE FROM agent_alerts     WHERE related_order  IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 5. Orders (cascades children: order_line_items, order_logs,
--    order_proof_documents, order_customer_portals, production_request_orders)
-- -----------------------------------------------------------------------------

DELETE FROM orders;

-- -----------------------------------------------------------------------------
-- 6. Customers (cascades customer_notes / tasks / activities /
--    buying_patterns; SET NULL for customer_assignments.customer_id)
-- -----------------------------------------------------------------------------

-- Stale customer_assignments rows now point at NULL customers; clean them up so
-- the agent CRM is empty before reseed.
DELETE FROM customer_assignments;

DELETE FROM customers;

COMMIT;

-- -----------------------------------------------------------------------------
-- Verify
-- -----------------------------------------------------------------------------

SELECT
  (SELECT COUNT(*) FROM customers)                  AS customers,
  (SELECT COUNT(*) FROM orders)                     AS orders,
  (SELECT COUNT(*) FROM order_line_items)           AS line_items,
  (SELECT COUNT(*) FROM invoices)                   AS invoices,
  (SELECT COUNT(*) FROM receivables)                AS receivables,
  (SELECT COUNT(*) FROM trips)                      AS trips,
  (SELECT COUNT(*) FROM trip_history)               AS trip_history,
  (SELECT COUNT(*) FROM material_consumption)       AS material_consumption,
  (SELECT COUNT(*) FROM order_proof_documents)      AS proofs,
  (SELECT COUNT(*) FROM agent_commissions)          AS agent_commissions,
  (SELECT COUNT(*) FROM agent_performance_snapshots) AS perf_snapshots;
